---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  - NPM_RUN_MOCHA=true
  - NPM_RUN_MOCHA=false

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - test "$NPM_RUN_MOCHA" != true || npm run mocha
  - test "$NPM_RUN_MOCHA" = true || npm test
