---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  - NPM_RUN_MOCHA=true
  - NPM_TEST=true

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - test "$NPM_RUN_MOCHA" != true || npm run mocha
  - test "$NPM_TEST" != true || npm test
